Added searching field
KESHAmambo/Trading pull request #4
Opened 2020-10-19 18:51 UTC by xnemetsx

2020-10-19 22:18 UTC, KESHAmambo requested changes

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> -      <SafeAreaView>
Зачем убрал SafeAreaView? Наверно, лучше внутрь него положить View

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
>          <Button title={'REFRESH'} onPress={onPress} />
Так, на будущее: тебе надо этот батон убрать - вместо него перезагрузка должна происходить при нажатии на пул ту рефреш

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> +          onChangeText={text => onChangeText(text)}
Стрелочная функция в разметке. Да еще и бесполезная. Можно просто onChangeText передать

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> +  const renderedPairs = useMemo(() => {
лучше назвать `filteredPairs`, а то по восприятию кажется, что у тебя там массив уже отрендеренных элементов пар лежит

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> +  const [inputValue, setInputValue] = useState('Search...');
не нужно плейсхолдер хранить в стейте. Для его отображения при пустом значении поля в компоненте TextInput  есть отдельная пропса

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
>          <Button title={'REFRESH'} onPress={onPress} />
Вообще, если уже есть аторелоуд, то рефреш по экшену можно не делать. Но тут для целей тренировки лучше замутить

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> +        pair.title.indexOf(inputValue.toUpperCase()) !== -1
title к апперкейсу перед сравнением

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> +    const curPairsInterval = setInterval(getCurPairs, 10000);
У тебя нет никакого состояния, которое бы отслеживало то, происходит ли сейчас загрузка.
Надо сделать так, чтобы эта индикация отображалась. По дизайну смотри сам, как лучше сделать. Но требования к индикации следующие: она не должна делать контент уже загруженный ранее недоступным.
Либа для отображения анимированных иконок: https://www.npmjs.com/package/lottie-react-native
Отсюда можешь брать готовые анимации: https://lottiefiles.com/featured

А еще важно следующее: пока происходит загрузка предыдущего запроса, не должен отправляться следующий (если это автообновление, то надо просто не вызывать getCurPairs)

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> +        <PairsList currencyPairs={renderedPairs}/>
Подсказка: у FlatList есть пропса, через которую можно задать исполняемую на pull-to-refresh  функцию.
А также есть пропса, которая при значении true отображает индикатор загрузки стандартный. Можешь пока что им воспользоваться, а через lottie факультативно отдельным ПР лучше сделаешь индикатор.

2020-10-19 22:18 UTC, KESHAmambo commented on features/main_screen/PairsList.tsx
>    const renderItem: ListRenderItem<ICurrencyPair> = (info) => {
функция переопределяется на каждый ререндер, соответственно, флет лист будет на каждый ререндер все элементы ререндерить - это негативно влияет на перформансе

2020-10-19 22:18 UTC, KESHAmambo commented on App.tsx
> +  const onChangeText = (text: string) => {
Тоже функция бесполезная, пока никаких других действий ты не делаешь. Ну и из-за того, что onChangeText переопределяется на каждый ререндер, ты по факту сделал только хуже, обернув setInputValue, потому что TextInput тоже на каждый ререндер будет переререндываться.

2020-10-19 22:25 UTC, xnemetsx commented on App.tsx
> -      <SafeAreaView>
ты сказал: то, что не знаешь, убирай. вот я и убрал)0

2020-10-22 21:29 UTC, KESHAmambo approved these changes

2020-10-22 21:31 UTC, merged