Added Redux
KESHAmambo/Trading pull request #6
Opened 2020-11-09 20:54 UTC by xnemetsx

2020-11-14 17:17 UTC, KESHAmambo requested changes

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/HomeScreen.tsx
> +      <StatusBar backgroundColor={BackgroundColor.APP}/>
статус бар, наверно, все-таки на любом экране отображается (если только ты никакого особоенного поведения сам не придумал, конечно), так что его надо в корневой компонент приложения вернуть

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/PairsList.tsx
> +    console.log('in useEffect')
В реальном проекте надо удалять логи, которые ставил для дебага, перед тем как залить ветку в основную

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/PairsList.tsx
> +    if (!isRefreshing) dispatch(fetchCurrencyPairs())
лучше везде после ифа блоки ставить, хотя это, скорее, чисто мое субъективное мнение

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/PairsList.tsx
> +  const isRefreshing = useSelector(selectStatus)
selectStatus лучше назвать isCurrencyPairsListRefreshingSelector:
- все селекторы с постфиксом Selector вроде принято называть (ну или как проект договорится)
- название более точно отображает суть, а это необходимо, так как будут и другие аналогичные селекторы других запросов

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/PairsList.tsx
> +    if (!isRefreshing) {
Так как хук на маунт отрабатыает, тут просто излишне писать проверку if (!isRefreshing)

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/pairsListSlice.ts
> +  'pairs/fetchCurrencyPairs',
для красоты лучше вынести префикс pairs в константу, и переиспользовать ее при наименовании (в том числе в createSlice)

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/pairsListSlice.ts
> +    return fetch('http://' + myNet.apiPath + '/currencies')
лучше сразу сделать функцию, которая будет принимать кастомный путь запроса (здесь это `/currencies`) и отдавать склеенный с базовым путем УРЛ

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/pairsListSlice.ts
> +import { createAsyncThunk, createSlice, SliceCaseReducers } from "@reduxjs/toolkit";
Файлы, относящиеся к редаксу, лучше объединить в одну папку общую (store, например). Внутри этой папки файл index (там объявляешь стор) и папка features, в которой хранится набор файлов: индекс, в котором слайс прописан, папка/файл с танками,  файл с селекторами.

2020-11-14 17:17 UTC, KESHAmambo commented on index.js
> +const ReduxApp = provideAppWithStore(App, store);
Функция это ни за чем, можно просто написать:
```
const ReduxApp = () => {
  return () => {
    return (
      <Provider store={store}>
        <App/>
      </Provider>
    )
  }
}
```

Или у тебя ТСные ошибки какие-то так были?

2020-11-14 17:17 UTC, KESHAmambo commented on features/home_screen/PairsList/pairsListSlice.ts
> +export default slice.reducer;
лучше export default не пользуйся, он, вроде как, ломает в чем-то тришейкинг (не шарю как, пожешь отдельно почитать, но это тупо за интерес)
а еще экспорты вебшторба в виде `export const pairsReducer = slice.reducer` распознаются замечательно, в то время как дефолтные - хреново

2020-11-14 17:17 UTC, KESHAmambo commented on redux_store/types.ts
> +export interface IPairsState {
Тип стейта конкретной фичи лучше хранить в ее папке (то есть лучше хранить типы в той области, где они используются, а вот если используются в разных местал, то тогда в корневой папке types  в соответствующей тематике подпапке)

2020-11-14 17:24 UTC, xnemetsx commented on features/home_screen/PairsList/PairsList.tsx
> +    console.log('in useEffect')
да я пропустил этот

2020-11-14 17:32 UTC, xnemetsx commented on index.js
> +const ReduxApp = provideAppWithStore(App, store);
Да, у меня так и остался тот ворнинг, о котором я тебе говорил. Я просто по-разному пытался обернуть в провайдер, но этот ворнинг никуда не исчез. Возможно из-за того, что у меня файл index с расширением js. Но это тайпскриптовый темплейт так сгенерировал

2020-11-30 22:03 UTC, merged

2020-11-30 22:43 UTC, KESHAmambo commented on store/features/pairsList/index.ts
> +export const pairsPrefix = 'pairs';
константы обычно пишут капсом и через нижние подчеркивания

2020-11-30 22:43 UTC, KESHAmambo commented on App.tsx
> +          <RootStack.Screen name={'Home'} component={HomeScreen}/>
Лучше имена экранов сразу тоже в енам выносить, потому что они будут переиспользоваться при навигации с других экранов

2020-11-30 22:43 UTC, KESHAmambo commented on App.tsx
> +          <RootStack.Screen name={'Home'} component={HomeScreen}/>
Вообще, общее правило, если название/строка переиспользуются, то либо в енамы, либо в константы (как лучше - на конкретику надо смотреть)

2020-11-30 22:43 UTC, KESHAmambo commented on features/home_screen/CurrencyPair/CurrencyPair.tsx
> +            bezier
лучше явно прописывай значение bezier={true}

2020-11-30 22:43 UTC, KESHAmambo commented on features/home_screen/CurrencyPair/CurrencyPair.tsx
> +            bezier
Ничего страшного в этом, вроде, нет, но так точно никто не придерется (типа меня)

2020-11-30 22:43 UTC, KESHAmambo commented on features/home_screen/CurrencyPair/CurrencyPair.tsx
> +            style={{
стили в файле со стилем должны лежать

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +          color: (opacity = 1) => `rgba(0, 255, 255, ${opacity})`,
стрелочные функции в пропсах могут влиять на перформанс, так что просто в отдельную функцию вынеси в  глобальный скоуп этого файла

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +          color: (opacity = 1) => `rgba(0, 255, 255, ${opacity})`,
То есть чтобы функция всегда была одна

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +        style={{
Стили прямо в компоненте

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairTitle/styles.ts
> +
лишние переносы

2020-11-30 22:43 UTC, KESHAmambo commented on mocks/get/chartData.js
> +    newDate.setTime(currentDate + (i * 1000 * 3600 * 24));
Это, конечно, мок, и правила написания по чистоте кода могут быть смягчены, но:
лучше всегда числа выносить в константы (по именам констант тогда можно будет проще понять, почему именно такие действия производятся с величинами: представь, если кто-то не знает, сколько в часе секунд)

2020-11-30 22:43 UTC, KESHAmambo commented on mocks/get/chartData.js
> +  const chartData = getRandomChartData(30);
числа между собой связаны (30), поэтому надо выносит в отдельную переменную/константу, чтобы при изменении менялось везде, где надо (может не ту быдешь менять, а типок, который не шарит, где еще надо изменить)

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +  const dayDurationInMilliseconds = 1000*3600*24;
пора уже в глобальную константу вынести, если в нескольких местах используешь

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +      style={{
стили в компоненте

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +      onStartShouldSetResponder={(event) => true}
стрелочные функции прямо в пропсах - уже говорил, что плохо.
Во всех таких местах, где функция может быть константой (не зависит от переменных из скоупа компонента) вынеси в константы

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +      <View style={{
стиль в компоненте

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +      <View style={{
стиль в компоненте

2020-11-30 22:43 UTC, KESHAmambo commented on features/pair_details_screen/PairChart/PairChart.tsx
> +const processColorWrapper: (color?: number | ColorValue) => ProcessedColorValue | null | undefined = (color) => {
вынести в отдельный файл с утилитами (так как явно можно и нужно в других местах переиспользовать)

2020-11-30 22:43 UTC, KESHAmambo commented on mocks/get/chartData.js
> +const nDays = 31;
четко, предвосхитил замечания, что я только оставил. Только назови константу капсом и андерскорами