Work in process
KESHAmambo/Trading pull request #7
Opened 2020-12-07 18:52 UTC by xnemetsx

2020-12-26 09:08 UTC, KESHAmambo requested changes

2020-12-26 09:08 UTC, KESHAmambo commented on features/pair_details_screen/PairDetailsScreen.tsx
> +  useEffect(() => {
Пустой useEffect остался.
Очевидные вещи больше писать не буду, ты все равно это понимаешь

2020-12-26 09:08 UTC, KESHAmambo commented on utilites/utilites.ts
> +export const DAY_DURATION_IN_MILLISECONDS = 1000 * 3600 * 24;
Константы нужно в константах хранить, а не в утилитах. (тут наверно это случайно оставил ты)

2020-12-26 09:08 UTC, KESHAmambo commented on utilites/utilites.ts
> +import { ColorValue, ProcessedColorValue } from "react-native-charts-wrapper/node_modules/@types/react-native";
лучше, конечно, называть утилиты более специфично. Вернее, лучше раскладывать в папке utilites все утилиты по специфичным папкам. Например, можно утилиты такого характера, как тут, положитьв папку utilites/typescript/[npm_module_name], потому что в данном конкретном случае функция помогает тебе обойти неудобство, созданное библиотекой (а именно тем, как печально  у нее получилось в этом месте заиспользовать тайпскрипт)

2020-12-26 09:08 UTC, KESHAmambo commented on utilites/utilites.ts
> +export const processColorWrapper: (color?: number | ColorValue) => ProcessedColorValue | null | undefined = (color) => {
Нужно к этой специфичной функции коммент добавить, нахрена она вообще нужна и почему появилась

2020-12-26 09:08 UTC, KESHAmambo commented on features/pair_details_screen/ExchangeWidget/ExchangeWidget.tsx
> +const PAYMENT_FEE_IN_PERCENT = 0.5;
Это значение нужно с сервера получать. Сделай какой-нибудь служебный сервис, который такое значение вместе с другими системными значениями, будет возвращать

2020-12-26 09:08 UTC, KESHAmambo commented on features/pair_details_screen/ExchangeWidget/ExchangeWidget.tsx
> +      <View style={styles.inputFieldContainer}>
У тебя инпут филд повторяется тут несколько раз  - это причина вынести в отдельный компонент. В целом, такие мелкие элементы, которые с высокой степенью вероятности будут переиспользоваться с дальнейшим развитием приложения, всегда нужно выносить в отдельные компоненты (хранить их где-нибудь в папке src/components  или src/elements (как по мне первое лучше подходит для тех переиспользуемых компонентов, которые внутри себя имеют некоторую бизнес-логику, а второе - для совсем тупых, которые в основном только верстку в себе несут и бизнес-логики в себе не имеют).

Под бизнес-логикой я тут имею в виду логику, которая характерная именно для этого приложения. Логика "движка" самого компонена не считается, так сказать)

2020-12-26 09:08 UTC, KESHAmambo commented on features/pair_details_screen/ExchangeWidget/ExchangeWidget.tsx
> +          <Pressable
С кнопкой то же самое - потенциально переиспользуемый компонент

2020-12-26 09:08 UTC, KESHAmambo commented on features/pair_details_screen/PairDetailsScreen.tsx
> +  useEffect(() => {
увидел - уже исправлено

2021-01-18 14:58 UTC, xnemetsx commented on features/pair_details_screen/ExchangeWidget/ExchangeWidget.tsx
> +      <View style={styles.inputFieldContainer}>
ну да, я уже успел поинтересоваться, что такое бизнес-логика в проге

2021-01-28 14:47 UTC, merged